/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lx_multimedialearn_openglstudy_xbo_pbo_PBORender */

#ifndef _Included_com_lx_multimedialearn_openglstudy_xbo_pbo_PBORender
#define _Included_com_lx_multimedialearn_openglstudy_xbo_pbo_PBORender
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
